//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public string UserName { get; set; }
        public string Pwd { get; set; }
        public System.DateTime ExpireTime { get; set; }
        public int Id { get; set; }
        public string Token { get; set; }
        public string RefreshToken { get; set; }
        public string Code { get; set; }
    }
}
